Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,24 +32,31 @@ runs:
     - name: Install wget
       shell: bash
       run: |
-        # Installing wget (only on Windows)...
-        if test "${{ runner.os }}" = 'Windows'; then choco install --no-progress --yes wget || exit 1; fi
+
     - name: Download ShellCheck
       shell: bash
       run: |
         # Downloading ShellCheck...
-        sc_ver="${{ inputs.shellcheck-version }}"
-        base_url="https://github.com/koalaman/shellcheck/releases/download/${sc_ver?}/shellcheck-${sc_ver?}"
-        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) exit 1; esac
+        annotate_error() { echo "::error file=action.yml,line=$1::Error $2"; }
 
+        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) exit 1; esac
+        action_path="${{ github.action_path }}"
+        sc_ver="${{ inputs.shellcheck-version }}"
+        base_url="https://github.com/koalaman/shellcheck/releases/download/${sc_ver?}/"
+        if test "${current_os}" = 'win'; then archive_name="shellcheck-${sc_ver?}.zip"; else archive_name="shellcheck-${sc_ver?}.${current_os?}.x86_64.tar.xz"; fi
+
+        annotate_error "$LINENO" 90
+        ## Installing wget (only on Windows)...
+        if test "${current_os}" = 'win'; then choco install --no-progress --yes wget 1>/dev/null || exit 2; fi
+
+        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || exit 3
         if test "${current_os}" = 'win'; then
-          wget -q -O 'shellcheck.zip' "${base_url?}.zip" || exit 2
-          unzip -ojq 'shellcheck.zip' '*' -d "./shellcheck-${sc_ver?}/" || exit 3
+          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || exit 4
         else
-          wget -qO- "${base_url?}.${current_os?}.x86_64.tar.xz" | tar -xJv 1>/dev/null || exit 2
+          tar –xJf "${archive_name?}" –C '.' || exit 4
         fi
-        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${{ github.action_path }}/"
-        rm -rf "./shellcheck-${sc_ver?}"
+        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${action_path?}/" || exit 5
+        rm -f "./${archive_name?}"; rm -rf "./shellcheck-${sc_ver?}"
     - name: Display ShellCheck version
       shell: bash
       run: |
