Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,7 +34,7 @@ runs:
       shell: bash
       run: |
         # Downloading ShellCheck...
-        annotate_error() { echo "::error file=action.yml,line=$2,col=1,endColumn=50::Error $1 on line $2"; exit "$1"; }
+        annotate_error() { echo "::error file=${{ github.action_path }}/action.yml,line=$2,col=1,endColumn=50::Error $1 on line $2"; exit "$1"; }
 
         case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) annotate_error 1 39; esac
         action_path="${{ github.action_path }}"
@@ -47,7 +47,7 @@ runs:
 
         wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 3 48
         if test "${current_os}" = 'win'; then
-          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || annotate_error 4 50
+          unzipX -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || annotate_error 4 50
         else
           tar -xf "${archive_name?}" || annotate_error 4 52
         fi
