Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,33 +29,28 @@ runs:
         # Set up matcher...
         matcher_file="${{ github.action_path }}/.github/matchers/tty/shellcheck-matcher.json"
         if test -f "${matcher_file}"; then echo "::add-matcher::${matcher_file}"; echo 'Matcher configured.'; fi
-    - name: Install wget
-      shell: bash
-      run: |
-
     - name: Download ShellCheck
       shell: bash
       run: |
         # Downloading ShellCheck...
-        annotate_error() { echo "::error file=action.yml,line=48,col=1,endColumn=7::Error $2"; }
+        annotate_error() { echo "::error file=action.yml,line=$2,col=1,endColumn=3::Error $1"; exit $1}
 
-        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) exit 1; esac
+        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) annotate_error 1 42; esac
         action_path="${{ github.action_path }}"
         sc_ver="${{ inputs.shellcheck-version }}"
         base_url="https://github.com/koalaman/shellcheck/releases/download/${sc_ver?}/"
         if test "${current_os}" = 'win'; then archive_name="shellcheck-${sc_ver?}.zip"; else archive_name="shellcheck-${sc_ver?}.${current_os?}.x86_64.tar.xz"; fi
 
-        annotate_error '48' 90
         ## Installing wget (only on Windows)...
-        if test "${current_os}" = 'win'; then choco install --no-progress --yes wget 1>/dev/null || exit 2; fi
+        if test "${current_os}" = 'win'; then choco install --no-progress --yes wget 1>/dev/null || annotate_error 2 49; fi
 
-        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || exit 3
+        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 3 51
         if test "${current_os}" = 'win'; then
-          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || exit 4
+          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || annotate_error 4 53
         else
-          tar –xJf "${archive_name?}" –C '.' || exit 4
+          tar –xJf "${archive_name?}" || annotate_error 4 55
         fi
-        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${action_path?}/" || exit 5
+        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${action_path?}/" || annotate_error 5 57
         rm -f "./${archive_name?}"; rm -rf "./shellcheck-${sc_ver?}"
     - name: Display ShellCheck version
       shell: bash
