Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -49,8 +49,8 @@ runs:
       shell: bash
       run: |
         # Downloading ShellCheck...
-        BASE_LINE='49'
-        annotate_error() { LINE="$(("${BASH_LINENO[0]}"+"${BASE_LINE}"-2))"; echo "::error::Error $1 in action.yml at line ${LINE}"; exit "$1"; }
+        BASE_LINE='52'
+        annotate_error() { LINE="$(("${BASH_LINENO[0]}"+"${BASE_LINE}"-2))"; echo "::error::Error $1 in action.yml at line ${LINE}" >&2; exit "$1"; }
 
         case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) annotate_error 1; esac
         action_path="${{ github.action_path }}"
@@ -64,7 +64,7 @@ runs:
         download_dir="${action_path?}/our_downloads"
         mkdir -p "${download_dir?}" || annotate_error 3
         cd "${download_dir?}" || annotate_error 4
-        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 5
+        wgetX -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 5
 
         archive_name="${download_dir?}/${archive_name?}"
         if test "${current_os}" = 'win'; then
